### ISSUE TITLE
Unexpected token, expected ";"

### ISSUE THREAD

**Issue by Shingaz** [babel/karma-babel-preprocessor#52]
The babel processor raises error on TypeScript types declarations. It doesn't happen with the same configuration with `karma-webpack` + `babel-loader`.

```
ERROR [preprocessor.babel]: filename.test.js: Unexpected token, expected ";" (10:11)

   8 | 
   9 | describe('describe', () => {
> 10 |   let model: JSONModel;

```

Karma configuration:
```
preprocessors: {
  'test/unit/**/*.test.ts': ['babelTypeScript', 'sourcemap'],
},
customPreprocessors: {
  babelTypeScript: {
    base: 'babel',
    options: {
      sourceMap: 'inline',
      presets: ['@babel/preset-env', '@babel/preset-typescript'],
      plugins: [
        '@babel/plugin-proposal-class-properties',
        '@babel/proposal-object-rest-spread',
        '@babel/plugin-proposal-optional-chaining',
        [
          '@babel/plugin-syntax-decorators',
          {
            decoratorsBeforeExport: true,
          },
        ],
      ],
      ignore: ['**/*.d.ts'],
    },
    filename: function (file) {
      return file.originalPath.replace(/\.ts$/, '.js');
    },
    sourceFileName: function (file) {
      return file.originalPath;
    },
  },
},
```

**Comment by MattiasBuelens** [comment]
Interesting! It looks like the problem is that we use the new `filename` both to [change the resulting `file.path`](https://github.com/babel/karma-babel-preprocessor/blob/0c21e97a6c43b6bc0c381b140fe688300a2ba919/lib/index.js#L18) and to [pass along as Babel options](https://github.com/babel/karma-babel-preprocessor/blob/0c21e97a6c43b6bc0c381b140fe688300a2ba919/lib/index.js#L20). However, since Babel now sees a `.js` extension in its `filename` option, it doesn't run it through the TypeScript transform plugin, and thus the TypeScript code ends up as-is in the final output! 😱

Similar preprocessors (such as `karma-typescript-preprocessor`) seem to handle this by [always passing the `originalPath` as `filename`](https://github.com/sergeyt/karma-typescript-preprocessor/blob/56b4533ed23bb15d44fb41fd24155d5c157f1f88/index.js#L24). I'll try something similar for this preprocessor.
